<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.message</groupId>
        <artifactId>instant-messaging-server</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>application</artifactId>
    <name>application</name>
    <url>http://maven.apache.org</url>

    <dependencies>

        <!-- 本地cache模块依赖 -->
        <dependency>
            <groupId>com.github.instant-messaging</groupId>
            <artifactId>cache</artifactId>
            <version>1.0.2</version>
        </dependency>
        <!-- 本地common模块依赖 -->
        <dependency>
            <groupId>com.github.instant-messaging</groupId>
            <artifactId>common</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.message</groupId>
            <artifactId>infrastructure</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        
        <!-- Netty依赖 -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>
        
        <!-- Lombok依赖 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        
        <!-- RocketMQ Spring Boot Starter -->
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.2.1</version>
        </dependency>
    </dependencies>
</project>
